//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libreria_de_conexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aprendiz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aprendiz()
        {
            this.Registro_Asistencias_QR = new HashSet<Registro_Asistencias_QR>();
            this.Soporte_asistencia = new HashSet<Soporte_asistencia>();
        }
    
        public int idAprendiz { get; set; }
        public string Nombres_Aprenidiz { get; set; }
        public string Apellidos_Aprendiz { get; set; }
        public string Email_Aprenidiz { get; set; }
        public string Tipo_Documento { get; set; }
        public string Numero_Documento { get; set; }
        public string Contraseña { get; set; }
        public string Estado { get; set; }
        public Nullable<int> Numero_Ficha { get; set; }
        public Nullable<int> idAdministrador { get; set; }
    
        public virtual Administrador Administrador { get; set; }
        public virtual Ficha Ficha { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registro_Asistencias_QR> Registro_Asistencias_QR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Soporte_asistencia> Soporte_asistencia { get; set; }
    }
}
