//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libreria_de_conexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reporte
    {
        public int idReporte { get; set; }
        public string Fecha_Reporte { get; set; }
        public string Hora_Reporte { get; set; }
        public Nullable<int> idAsistencia { get; set; }
    
        public virtual Registro_Asistencias_QR Registro_Asistencias_QR { get; set; }
    }
}
