//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libreria_de_conexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soporte_asistencia
    {
        public int idSoporte { get; set; }
        public Nullable<int> idAprendiz { get; set; }
        public byte[] Archivo_soporte { get; set; }
        public string Extension { get; set; }
        public Nullable<int> idAsistencia { get; set; }
        public Nullable<System.DateTime> Fecha_Hora { get; set; }
    
        public virtual Aprendiz Aprendiz { get; set; }
        public virtual Registro_Asistencias_QR Registro_Asistencias_QR { get; set; }
    }
}
